name: Run Lint

on:
    push:
        branches: [main]
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        env:
          SKIP: no-commit-to-branch
        steps:
            - uses: actions/checkout@v4

            - name: Setup Git
              run: |
                apt-get update
                apt-get install -y git

            - name: Install uv
              uses: astral-sh/setup-uv@v4
              with:
                version: "0.5.7"
                enable-cache: true

            - name: Set up Python
              run: uv python install

            - name: Install project
              run: uv sync --group lint

            - name: Run Lint (pre-commit)
              run: uv run pre-commit run --all-files
